# MySQL. Ensure the mysql2 gem is defined in your Gemfile
# gem "mysql2"

default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USERNAME'] %> # MySQLのユーザー名
  password: <%= ENV['DATABASE_PASSWORD'] %> # MySQLのパスワード
  host: <%= ENV['DATABASE_HOST'] %> # MySQLのホスト名（例: localhost）

development:
  <<: *default
  database: photo_app_development

test:
  <<: *default
  database: photo_app_test

production:
  <<: *default
  database: photo_app_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
